group: bluezone
sudo: required
language: node_js
node_js: "8"
notifications:
  slack: ibm-aic-offerings:pKEkgH3hXaZQg8UCl6eLWyYB
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn install && npm run test
